package com.webwemser.web;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 14/06/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class FBCuserContentData extends FBCdataTransferObject implements KvmSerializable
{

    
    public KILuserPersistenceData poster;
    
    public String text;
    
    public Long timestamp=0L;

    public FBCuserContentData ()
    {
    }

    public FBCuserContentData (Object paramObj,FBCExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("poster"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.poster = (KILuserPersistenceData)__envelope.get(j,KILuserPersistenceData.class);
                    }
                    continue;
                }
                if (info.name.equals("text"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.text = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.text = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("timestamp"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.timestamp = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.timestamp = (Long)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.poster!=null?this.poster:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.text!=null?this.text:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return timestamp;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = KILuserPersistenceData.class;
            info.name = "poster";
            info.namespace= "";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "text";
            info.namespace= "";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "timestamp";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
