package com.webwemser.web;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 15/06/2016
//
//---------------------------------------------------


/**
 * Generated using easywsdl.com
 * @author Jannik, Christian
 */
public interface IServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
