package com.webwemser.web;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 14/06/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class KILconversationData extends KILuserContentData implements KvmSerializable
{


    public Integer id=0;

    public Integer origin=0;

    public ArrayList<KILreplyData> replies =new ArrayList<KILreplyData>();

    public KILconversationData ()
    {
    }

    public KILconversationData (java.lang.Object paramObj,KILExtendedSoapSerializationEnvelope __envelope)
    {
        super(paramObj, __envelope);
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue();
                if (info.name.equals("id"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.id = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.id = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("origin"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.origin = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.origin = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("replies"))
                {
                    if(obj!=null)
                    {


                        if(this.replies==null)
                        {
                            this.replies = new ArrayList<KILreplyData>();
                        }
                        java.lang.Object j =obj;
                        KILreplyData j1= (KILreplyData)__envelope.get(j,KILreplyData.class);
                        this.replies.add(j1);


                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return id;
        }
        if(propertyIndex==count+1)
        {
            return origin;
        }
        if(propertyIndex>=count+2 && propertyIndex< count+ 2+this.replies.size())
        {
            return this.replies.get(propertyIndex-(count+2));
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+2+replies.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "id";
            info.namespace= "";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "origin";
            info.namespace= "";
        }
        if(propertyIndex>=count+2 && propertyIndex <= count+2+this.replies.size())
        {
            info.type = KILreplyData.class;
            info.name = "replies";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    public ArrayList<KILreplyData> getReplies(){
        return replies;
    }

}
