package com.webwemser.web;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.5.2
//
// Created by Quasar Development at 29/05/2016
//
//---------------------------------------------------



public interface KILIServiceEvents
{
    public void Starting();
    public void Completed(KILOperationResult result);
}
