package com.webwemser.web;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.5.2
//
// Created by Quasar Development at 29/05/2016
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class KILOnlineIntegrationServiceSoapBinding
{
    interface KILIWcfMethod
    {
        KILExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://10.0.2.2:8080/letsmeet/OnlineIntegration";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    KILIServiceEvents callback;
    public KILOnlineIntegrationServiceSoapBinding(){}

    public KILOnlineIntegrationServiceSoapBinding (KILIServiceEvents callback)
    {
        this.callback = callback;
    }
    public KILOnlineIntegrationServiceSoapBinding(KILIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public KILOnlineIntegrationServiceSoapBinding(KILIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected KILExtendedSoapSerializationEnvelope createEnvelope()
    {
        KILExtendedSoapSerializationEnvelope envelope= new KILExtendedSoapSerializationEnvelope(KILExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,KILExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,KILExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public KILsessionResponse login(final String arg0,final String arg1 ) throws java.lang.Exception
    {
        return (KILsessionResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "login");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILsessionResponse)getResult(KILsessionResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, KILOperationResult< KILsessionResponse>> loginAsync(final String arg0,final String arg1)
    {
        return executeAsync(new KILFunctions.IFunc< KILsessionResponse>() {
            public KILsessionResponse Func() throws java.lang.Exception {
                return login( arg0,arg1);
            }
        });
    }
    
    public KILmeetsResponse getMeetsByUser(final String arg0 ) throws java.lang.Exception
    {
        return (KILmeetsResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getMeetsByUser");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILmeetsResponse)getResult(KILmeetsResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, KILOperationResult< KILmeetsResponse>> getMeetsByUserAsync(final String arg0)
    {
        return executeAsync(new KILFunctions.IFunc< KILmeetsResponse>() {
            public KILmeetsResponse Func() throws java.lang.Exception {
                return getMeetsByUser( arg0);
            }
        });
    }
    
    public KILmeetsResponse getMeetsByCategory(final String arg0,final String arg1 ) throws java.lang.Exception
    {
        return (KILmeetsResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getMeetsByCategory");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILmeetsResponse)getResult(KILmeetsResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, KILOperationResult< KILmeetsResponse>> getMeetsByCategoryAsync(final String arg0,final String arg1)
    {
        return executeAsync(new KILFunctions.IFunc< KILmeetsResponse>() {
            public KILmeetsResponse Func() throws java.lang.Exception {
                return getMeetsByCategory( arg0,arg1);
            }
        });
    }
    
    public void init( ) throws java.lang.Exception
    {
        execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "init");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, KILOperationResult< Void>> initAsync()
    {
        return executeAsync(new KILFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                init( );
                return null;
            }
        }) ;
    }
    
    public KILmeetResponse getMeet(final String arg0,final Integer arg1 ) throws java.lang.Exception
    {
        return (KILmeetResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getMeet");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(arg1);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILmeetResponse)getResult(KILmeetResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, KILOperationResult< KILmeetResponse>> getMeetAsync(final String arg0,final Integer arg1)
    {
        return executeAsync(new KILFunctions.IFunc< KILmeetResponse>() {
            public KILmeetResponse Func() throws java.lang.Exception {
                return getMeet( arg0,arg1);
            }
        });
    }
    
    public KILmeetResponse leaveMeet(final String arg0,final Integer arg1 ) throws java.lang.Exception
    {
        return (KILmeetResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "leaveMeet");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(arg1);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILmeetResponse)getResult(KILmeetResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, KILOperationResult< KILmeetResponse>> leaveMeetAsync(final String arg0,final Integer arg1)
    {
        return executeAsync(new KILFunctions.IFunc< KILmeetResponse>() {
            public KILmeetResponse Func() throws java.lang.Exception {
                return leaveMeet( arg0,arg1);
            }
        });
    }
    
    public KILsessionResponse register(final String arg0,final String arg1,final String arg2 ) throws java.lang.Exception
    {
        return (KILsessionResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "register");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg2";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg2!=null?arg2:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILsessionResponse)getResult(KILsessionResponse.class,__result,"return",__envelope);
            }
        },"");
    }
     /*
    public android.os.AsyncTask< Void, Void, KILOperationResult< String>> registerAsync(final String arg0,final String arg1,final String arg2)
    {

        return executeAsync(new KILFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return register( arg0,arg1,arg2);
            }
        });

    }

    */
    
    public KILmeetResponse joinMeet(final String arg0,final int arg1 ) throws java.lang.Exception
    {
        return (KILmeetResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "joinMeet");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(arg1>-1?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILmeetResponse)getResult(KILmeetResponse.class,__result,"return",__envelope);
            }
        },"");
    }

    public KILmeetsResponse getMeets(final String arg0,final long arg1,final long arg2 ) throws java.lang.Exception
    {
        return (KILmeetsResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getMeets");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.LONG_CLASS;
                __info.setValue(arg1>0?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg2";
                __info.type=PropertyInfo.LONG_CLASS;
                __info.setValue(arg2>0?arg2:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILmeetsResponse)getResult(KILmeetsResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public KILmeetResponse createMeet(final String arg0,final String arg1,final String arg2,final String arg3,final String arg4,final long arg5,final int arg6 ) throws java.lang.Exception
    {
        return (KILmeetResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "createMeet");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg2";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg2!=null?arg2:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg3";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg3!=null?arg3:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg4";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg4!=null?arg4:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg5";
                __info.type=PropertyInfo.LONG_CLASS;
                __info.setValue(arg5>0?arg5:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg6";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(arg6>0?arg6:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILmeetResponse)getResult(KILmeetResponse.class,__result,"return",__envelope);
            }
        },"");
    }

    public KILcategoriesResponse getCategories(final String arg0 ) throws java.lang.Exception
    {
        return (KILcategoriesResponse)execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getCategories");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILcategoriesResponse)getResult(KILcategoriesResponse.class,__result,"return",__envelope);
            }
        },"");
    }

    public KILreturnCodeResponse logout(final String arg0 ) throws java.lang.Exception
    {
        return (KILreturnCodeResponse) execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "logout");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILreturnCodeResponse)getResult(KILreturnCodeResponse.class,__result,"return",__envelope);
            }
        },"");
    }

    protected java.lang.Object execute(KILIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        KILExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, KILOperationResult< T>>  executeAsync(final KILFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, KILOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected KILOperationResult< T> doInBackground(Void... params) {
                KILOperationResult< T> result = new KILOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(KILOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,KILExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }

    public KILsessionResponse updateUserDescription(final String arg0, final String arg1) throws java.lang.Exception {
        return (KILsessionResponse) execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "updateUserDescription");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILsessionResponse)getResult(KILsessionResponse.class,__result,"return",__envelope);
            }
        },"");
    }

    public KILsessionResponse updateUserPassword(final String arg0, final String arg1) throws java.lang.Exception {
        return (KILsessionResponse) execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "updateUserPassword");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILsessionResponse)getResult(KILsessionResponse.class,__result,"return",__envelope);
            }
        },"");
    }

    public KILreturnCodeResponse deleteUser(final String arg0 ) throws java.lang.Exception
    {
        return (KILreturnCodeResponse) execute(new KILIWcfMethod()
        {
            @Override
            public KILExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                KILExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "deleteUser");
                __envelope.setOutputSoapObject(__soapReq);
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(KILExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (KILreturnCodeResponse)getResult(KILreturnCodeResponse.class,__result,"return",__envelope);
            }
        },"");
    }
}


