package com.webwemser.web;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 15/06/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

/**
 * MeetsResponse from server
 * generated using easywsdl.com
 * @author Christian, Jannik
 */
public class MeetsResponse extends SessionResponse implements KvmSerializable
{

    
    public ArrayList<MeetData> meets =new ArrayList<MeetData>();

    public MeetsResponse()
    {
    }

    public MeetsResponse(Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("meets"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.meets==null)
                        {
                            this.meets = new ArrayList<MeetData>();
                        }
                        Object j =obj;
                        MeetData j1= (MeetData)__envelope.get(j,MeetData.class);
                        this.meets.add(j1);
                   
        
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=count+0 && propertyIndex< count+ 0+this.meets.size())
        {
            return this.meets.get(propertyIndex-(count+0));
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+0+meets.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex>=count+0 && propertyIndex <= count+0+this.meets.size())
        {
            info.type = MeetData.class;
            info.name = "meets";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    /**
     * Gets all the MeetData instances of this response
     * @return
     */
    public ArrayList<MeetData> getMeets() {
        return meets;
    }

}
